= Webpage with Google Charts and Data from MySQL (greta)
E. Sandbling

Get http://greger.sandbling.se[Greta] the show a webpage with a https://developers.google.com/chart/[Google Chart (gauge)] with data supplied from a MySQL database located on a server hosted by Loopia.

== Change Log
2017-11-15::
Item created.


== Goals
* [ ] Replace static data in <<DataTable>> with dynamic data from MySQL source
* [ ] Limit the "exposed code", e.g. data source etc.

== General notes
Source: https://www.agcross.com/2015/01/connecting-a-google-chart-to-a-mysql-database-part-1/

== DataTables
https://developers.google.com/chart/interactive/docs/reference#DataTable[DataTables] are input data used to render data in Google Charts.

DataTables can be constructed in different ways (two?).
The most common, and most human readable is using the '_Javascript_' method.
A method more suited for database connection is the '_object litera notation_', or http://www.json.org/[JASON].
This method is better suited to generate through code.

=== Hand-coded Javascript
  var data = new google.visualization.DataTable();
    data.addColumn('string', 'Task');
    data.addColumn('number', 'Hours per Day');
    data.addRows([
      ['Work', 11],
      ['Eat', 2],
      ['Commute', 2],
      ['Watch TV', 2],
      ['Sleep', {v:7, f:'7.000'}]
    ]);

=== Object Literal Notation (JSON)
  var data = new google.visualization.DataTable(
      {
      cols: [{id: 'task', label: 'Task', type: 'string'},
             {id: 'hours', label: 'Hours per Day', type: 'number'}],
      rows: [{c:[{v: 'Work'}, {v: 11}]},
             {c:[{v: 'Eat'}, {v: 2}]},
             {c:[{v: 'Commute'}, {v: 2}]},
             {c:[{v: 'Watch TV'}, {v:2}]},
             {c:[{v: 'Sleep'}, {v:7, f:'7.000'}]}
            ]
      }, 0.6);

2017-11-15::
*_Stoped Here_* - pending "`How to Create a PHP and MySQL based Webpage`"