= Create a PHP and MySQL driven Webpage hosted at Loopia
E. Sandbling

The basics of creating a PHP and MySQL driven webpage hosted at loopia (http://greger.sandbling.se)

== Change Log
2017-11-15::
Item created.

== Sources
PHP/MySQL Tutorial::
http://www.freewebmasterhelp.com/tutorials/phpmysql

MySQLi at Loopia::
https://support.loopia.se/wiki/mysqli/

MySQLi Tutorial::
https://www.tutorialspoint.com/mysqli/

== General Notes

Classic MySQL functions will from PHP version 7 (only at Loopia?) stop being supported.

Instead MySQLi nust be used to manage DB connections.

=== Security
PHP code is processed by the server before it is sent to the browser, i.e. passwords and usernames declared in the `php` file will never be accessible from a browser connection.

The same goes for the source code. This too is not accessible from the browser.

  $username="username";
  $password="password";
  $database="your_database";

  mysql_connect(localhost,$username,$password);
  
=== Syntax
All `php` code must be enclosed by start and end tags.

  <?php
  code goes here...
  ?>

A shorthand version of the tags are available by omitting `php`, i.e. `<? ... ?>`.

However this notation may be missinterpreted by some servers.