:toc:
:toclevels: 5

= Documentation Main Page

This folder will provide material for documentation.

== About

As this project is mainly intended and created with personal use of the author _(me)_ in mind, the documentation is thus intended in line with this use. The documentation will in in this capacity mainly serve as an aid to memory during the development of this project.

=== Exploring the Options

A good documentation is important to maintain a coherent and transparent project. This is established, by what does this mean? - Well in my humble experience this always comes down to semantics and markup, i.e. what language you use and how.

Exploring the options available to create and maintain documentations in an efficient and convenient way I came across the markup language http://asciidoc.org[AsciiDoc]. This markup appealed to me right from the start as it offered the intuitiveness I wanted.

=== Documentation Hypothesis

Given above the documentation shall fulfill the following criteria.
